---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    webapp: httpd
    created: yashwanth
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels:
        webapp: httpd
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 9090
...
